# Generated by Django 2.2.2 on 2020-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20201205_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(blank=True, max_length=526, null=True, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='result_path',
            field=models.CharField(blank=True, max_length=526, null=True, verbose_name='Путь до результата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_path',
            field=models.CharField(blank=True, max_length=526, null=True, verbose_name='Путь до сырья'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='origin_path',
            field=models.CharField(blank=True, max_length=526, null=True, verbose_name='Директория из'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='result_path',
            field=models.CharField(blank=True, max_length=526, null=True, verbose_name='Директория в'),
        ),
    ]
