# Generated by Django 2.2.2 on 2020-12-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_auto_20201206_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='success',
        ),
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.CharField(max_length=64, null=True, verbose_name='Статус выполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='task_status',
            field=models.CharField(max_length=64, null=True, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images/', verbose_name='Изображение'),
        ),
    ]
