# Generated by Django 2.2.2 on 2020-12-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_auto_20201206_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Статус выполнения'),
        ),
    ]
