# Generated by Django 2.2.2 on 2020-12-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_auto_20201206_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extension',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Расширение'),
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='order',
            name='path',
            field=models.CharField(blank=True, max_length=526, null=True, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='order',
            name='process_inputed_geodata',
            field=models.BooleanField(default=False, verbose_name='Обработать введенные геоданные'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер файла'),
        ),
        migrations.AddField(
            model_name='order',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='string_geodata',
            field=models.TextField(blank=True, null=True, verbose_name='Геоданные файла'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
