# Generated by Django 2.2.2 on 2020-12-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0006_auto_20201211_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imputed_geodata',
            field=models.TextField(blank=True, null=True, verbose_name='Геоданные файла'),
        ),
    ]
