# Generated by Django 2.2.2 on 2020-12-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_order_imputed_geodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='imputed_geodata',
            field=models.TextField(blank=True, null=True, verbose_name='Ввести геоданные файла вручную'),
        ),
    ]
