# Generated by Django 2.2.2 on 2020-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_auto_20201211_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='length',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='imputed_geodata',
            new_name='inputed_geodata',
        ),
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='upload_images/', verbose_name='Изображение', width_field='width'),
        ),
    ]
