# Generated by Django 2.2.2 on 2020-12-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0009_auto_20201212_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='path',
        ),
        migrations.AddField(
            model_name='order',
            name='result_folder_path',
            field=models.CharField(blank=True, max_length=526, null=True, verbose_name='Путь до папки для сохранения результата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
    ]
